QCheckBox {
    font-size: 14px;
    color: #000000;
}

QCheckBox::indicator:unchecked {
    image: url(:/theme/light/image/checkbox_unchecked.png);
}

QCheckBox::indicator:unchecked:hover {
    image: url(:/theme/light/image/checkbox_unchecked_hover.png);
}

QCheckBox::indicator:unchecked:pressed {
    image: url(:/theme/light/image/checkbox_unchecked_hover.png);
}

QCheckBox::indicator:unchecked:!enabled {
    image: url(:/theme/light/image/checkbox-unchecked-insensitive.png);
}

QCheckBox::indicator:checked {
    image: url(:/theme/light/image/checkbox_checked.png);
}

QCheckBox::indicator:checked:hover {
    image: url(:/theme/light/image/checkbox_checked_hover.png);
}

QCheckBox::indicator:checked:pressed {
    image: url(:/theme/light/image/checkbox_checked_hover.png);
}

QCheckBox::indicator:checked:!enabled {
    image: url(:/theme/light/image/checkbox-checked-insensitive.png);
}
