#!/bin/bash

rvern="$(./vcs-revno)"
mingwb="$(ls /usr/ | grep mingw32 | grep -v amd64 | head --lines 1)"
qt5path="/opt/qt5-static/mingw/5.3"
if [ ! -d release ]
then
mkdir release
fi

$qt5path/bin/lrelease deepin-usb-creator.pro
./qmake-linux
make
$mingwb-strip --strip-all deepin-usb-creator
#mv deepin-usb-creator release/deepin-usb-creator-linux-$rvern
#./upx --lzma release/deepin-usb-creator-linux-$rvern

