#!/bin/bash

if [ ! -d release ]
then
mkdir release
fi
qtpath="."
qlupdate=$qtpath/bin/lupdate
qlrelease=$qtpath/bin/lrelease
qqmake=$qtpath/bin/qmake
$qlupdate deepin-usb-creator.pro
$qlrelease deepin-usb-creator.pro

$qqmake -config release -spec macx-g++
make
./fix-deepin-usb-creator-frameworkpaths.rb
mv deepin-usb-creator.app deepin-usb-creator-old.app
ditto --arch i386 deepin-usb-creator-old.app deepin-usb-creator.app
rm -r deepin-usb-creator-old.app

revno=$(./vcs-revno)
zip -r deepin-usb-creator-mac-$revno.zip deepin-usb-creator.app
mv deepin-usb-creator-mac-$revno.zip release

