#!/bin/bash

rvern="$(./vcs-revno)"
mingwb="$(ls /usr | grep mingw32 | grep -v amd64 | head --lines 1)"
#mingwb="$(pwd)/mxe-4/usr/bin/"$mingwb
#qtwind="$(pwd)/qt4-win"
#qt5path="$(pwd)/qt4-x11"
qt5path="/opt/qt5-static/mingw/5.3"

if [ ! -d release ]
then
mkdir release
fi

if [ ! -f "sevnz.dll" ] || [ ! -f "sevnz.exe" ]
then
svloc=$(wget "http://7-zip.org/" -O - | grep --ignore-case "a href=\"http://downloads.sourceforge.net/sevenzip/" | grep -v ".msi" | grep -v "x64" | tail --lines 1 | tr "<" "\n" | tr ">" "\n" | tr "\"" "\n" | grep "http://downloads.sourceforge.net/sevenzip/")
wget "$svloc" -O sevenzip.exe
svxloc=$(echo "$svloc" | sed 's/.exe/_extra.7z/')
wget "$svxloc" -O sevenzip-extra.7z
7z e -y sevenzip.exe 7z.exe 7z.dll
mv 7z.exe sevnz.exe
mv 7z.dll sevnz.dll
7z e -y sevenzip-extra.7z 7zS.sfx
fi

$qt5path/bin/lrelease deepin-usb-creator.pro
./qmake-windows
make
$mingwb-strip --strip-all release/deepin-usb-creator.exe
mv release/deepin-usb-creator.exe release/deepin-usb-creator-windows-$rvern.exe
./upx --lzma release/deepin-usb-creator-windows-$rvern.exe

