#!/bin/bash

qtPath=/opt/qt5-static/5.3/linuxg64
qtBin=$qtPath/bin

qtlupdate=$qtBin/lupdate
qtlrelease=$qtBin/lrelease
qtlconvert=$qtBin/lconvert

$qtlupdate deepin-boot-maker.pro

tslist=`ls *.ts`
for ts in $tslist
do
    $qtlconvert -i $ts -if ts -o ${ts%.*}.po -of po
done

cp en_US.po deepin-boot-maker.pot



