#!/bin/bash

qtPath=/opt/qt5-static/5.3/linuxg64
qtPath=/opt/qtstatic/5.3/linuxg64
qtBin=$qtPath/bin

qtlupdate=lupdate
qtlrelease=lrelease
qtlconvert=lconvert

$qtlupdate deepin-boot-maker.pro

tslist=`ls po/*.ts`
for ts in $tslist
do
    $qtlconvert -i $ts -if ts -o ${ts%.*}.po -of po
done

cp po/en_US.po po/deepin-boot-maker.pot



