#!/bin/bash

qtPath=/opt/qt5-static/5.3/linuxg64
qtBin=$qtPath/bin

qtlupdate=$qtBin/lupdate
qtlrelease=$qtBin/lrelease
qtlconvert=$qtBin/lconvert

$qtlupdate deepin-boot-maker.pro

tslist=`ls po/*.ts`
for ts in $tslist
do
    rm $ts
    $qtlconvert -i ${ts%.*}.po -if po -o $ts -of ts
done

$qtlrelease deepin-boot-maker.pro


