#!/bin/sh

#qtwind="$(pwd)/qt4-win"
#qt5path="$(pwd)/mxe-4/usr/i686-pc-mingw32/qt"
qt5path="/opt/qt5-static/mingw/5.3"
mingwb="$(ls /usr | grep mingw32 | grep -v amd64 | head --lines 1)"
$qt5path/bin/qmake -config release -spec $qt5path/mkspecs/win32-g++ "DEFINES += STATICWINDOWS" "QMAKE_CC = $mingwb-gcc" "QMAKE_CXX = $mingwb-g++" "QMAKE_INCDIR_QT = $qtwind/include" "QMAKE_LIBDIR_QT = $qtwind/lib" "QMAKE_LINK = $mingwb-g++" "QMAKE_COPY_DIR = cp -r" "QMAKE_COPY = cp" "QMAKE_COPY_DIR = cp -r" "QMAKE_MOVE = mv" "QMAKE_DEL_FILE = rm" "QMAKE_CHK_DIR_EXISTS = test -d" "QMAKE_QMAKE = $qt5path/bin/qmake" "QMAKE_MOC = $qt5path/bin/moc" "QMAKE_UIC = $qt5path/bin/uic" "QMAKE_RCC = $qt5path/bin/rcc" "QMAKE_RC = $mingwb-windres" "RESOURCES += unetbootin-windows.qrc unetbootin-sevnz.qrc" "QMAKE_LFLAGS += -Wl,-subsystem,windows" "$@"
#"RC_FILE += ubnembed.rc" "$@"
