#!/bin/bash

qt5path="/opt/qt5-static/5.3/linux32"
qtupdate=$qt5path/bin/lupdate
qtrelease=$qt5path/bin/lrelease
qtconvert=$qt5path/bin/lconvert

$qtupdate deepin-usb-creator.pro

$qtupdate qml/main.qml -ts qml_en_US.ts
$qtconvert deepin-usb-creator_en_US.ts qml_en_US.ts -o deepin-usb-creator_en_US.ts

$qtupdate qml/main.qml -ts qml_zh_CN.ts
$qtconvert deepin-usb-creator_zh_CN.ts qml_zh_CN.ts -o deepin-usb-creator_zh_CN.ts

$qtupdate qml/main.qml -ts qml_zh_TW.ts
$qtconvert deepin-usb-creator_zh_TW.ts qml_zh_TW.ts -o deepin-usb-creator_zh_TW.ts

$qtrelease deepin-usb-creator.pro
