name: Call License and README Check
on:
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: write
  contents: read

concurrency:
  group: ${{ github.workflow }}-pull/${{ github.event.number }}
  cancel-in-progress: true

jobs:
  license-check:
    uses: linuxdeepin/.github/.github/workflows/license-check.yml@master
