name: Call build-distribution
on:
  push:
    paths-ignore:
      - ".github/workflows/**"
  pull_request_target:
    paths-ignore:
      - ".github/workflows/**"

jobs:
  check_job:
    uses: linuxdeepin/.github/.github/workflows/build-distribution.yml@master
    secrets: inherit
