name: Call License and README Check
on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-pull/${{ github.event.number }}
  cancel-in-progress: true

jobs:
  license-check:
    uses: linuxdeepin/.github/.github/workflows/license-check.yml@master
