name: Call CLA check
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened, closed, synchronize]

concurrency:
  group: ${{ github.workflow }}-pull/${{ github.event.number }}
  cancel-in-progress: true

jobs:
  clacheck:
    uses: linuxdeepin/.github/.github/workflows/cla-check.yml@master
    secrets: inherit
