name: chatOps
on:
  issue_comment:
    types: [created]

jobs:
  chatopt:
    uses: linuxdeepin/.github/.github/workflows/chatOps.yml@master
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
